public class TriggerEventsConcept {
    public void InsertFunction(List<Case> c ){
        for(Case Clist : c){
            
            system.debug('case Record'+Clist);
        }
    }
    public void UpdateFunction(List<Case> c ){
        for(Case Clist : c){
            
            system.debug('case Record'+Clist);
        }
    }
    
    
    public void DeleteFunction(List<Case> c){
        for(Case Clist : c){
            
            system.debug('case Record'+Clist);
        }
    }
    
    public void unDeleteFunction(List<Case> c){
        for(Case Clist : c){
            
            system.debug('case Record'+Clist);
        }
    }
}